export default {
  plugins: ['stylelint-order'],

  overrides: [
    {
      files: ['**/*.vue'],
      customSyntax: 'postcss-html',
    },
    {
      files: ['**/*.scss'],
      customSyntax: 'postcss-scss',
    },
  ],

  rules: {
    'order/order': [
      [
        'custom-properties',
        {
          type: 'at-rule',
          name: 'extend',
        },
        {
          type: 'at-rule',
          name: 'include',
        },
        'declarations',
        'rules',
      ],
      {
        severity: 'warning',
      },
    ],

    'order/properties-order': [
      [
        {
          groupName: 'positioning',
          emptyLineBefore: 'never',
          noEmptyLineBetween: true,
          properties: [
            'position',
            'inset',
            'inset-block',
            'inset-inline',
            'top',
            'right',
            'bottom',
            'left',
            'z-index',
          ],
        },
        {
          groupName: 'layout',
          emptyLineBefore: 'always',
          noEmptyLineBetween: true,
          properties: [
            'display',
            'visibility',
            'overflow',
            'overflow-x',
            'overflow-y',
            'flex',
            'flex-grow',
            'flex-shrink',
            'flex-basis',
            'flex-flow',
            'flex-direction',
            'flex-wrap',
            'align-content',
            'align-items',
            'align-self',
            'justify-content',
            'justify-items',
            'justify-self',
            'order',
            'gap',
            'row-gap',
            'column-gap',
            'grid',
            'grid-template',
            'grid-template-columns',
            'grid-template-rows',
            'grid-column',
            'grid-row',
            'place-content',
            'place-items',
            'place-self',
          ],
        },
        {
          groupName: 'dimensions',
          emptyLineBefore: 'always',
          noEmptyLineBetween: true,
          properties: [
            'box-sizing',
            'width',
            'min-width',
            'max-width',
            'height',
            'min-height',
            'max-height',
            'aspect-ratio',
          ],
        },
        {
          groupName: 'spacing',
          emptyLineBefore: 'always',
          noEmptyLineBetween: true,
          properties: [
            'margin',
            'margin-block',
            'margin-inline',
            'margin-top',
            'margin-right',
            'margin-bottom',
            'margin-left',
            'padding',
            'padding-block',
            'padding-inline',
            'padding-top',
            'padding-right',
            'padding-bottom',
            'padding-left',
          ],
        },
        {
          groupName: 'visual',
          emptyLineBefore: 'always',
          noEmptyLineBetween: true,
          properties: [
            'border',
            'border-width',
            'border-style',
            'border-color',
            'border-top',
            'border-right',
            'border-bottom',
            'border-left',
            'border-radius',
            'outline',
            'outline-offset',
            'background',
            'background-color',
            'background-image',
            'background-position',
            'background-repeat',
            'background-size',
            'box-shadow',
            'opacity',
          ],
        },
        {
          groupName: 'typography',
          emptyLineBefore: 'always',
          noEmptyLineBetween: true,
          properties: [
            'color',
            'font',
            'font-family',
            'font-size',
            'font-style',
            'font-weight',
            'font-variant',
            'line-height',
            'letter-spacing',
            'text-align',
            'text-decoration',
            'text-indent',
            'text-overflow',
            'text-shadow',
            'text-transform',
            'white-space',
            'word-break',
            'word-wrap',
          ],
        },
        {
          groupName: 'interaction',
          emptyLineBefore: 'always',
          noEmptyLineBetween: true,
          properties: [
            'appearance',
            'cursor',
            'pointer-events',
            'resize',
            'user-select',
            'touch-action',
          ],
        },
        {
          groupName: 'content',
          emptyLineBefore: 'always',
          noEmptyLineBetween: true,
          properties: [
            'content',
            'object-fit',
            'object-position',
            'list-style',
          ],
        },
        {
          groupName: 'animation',
          emptyLineBefore: 'always',
          noEmptyLineBetween: true,
          properties: [
            'transform',
            'transform-origin',
            'transition',
            'transition-delay',
            'transition-duration',
            'transition-property',
            'transition-timing-function',
            'animation',
            'animation-name',
            'animation-duration',
            'animation-delay',
            'animation-timing-function',
            'animation-iteration-count',
          ],
        },
      ],
      {
        unspecified: 'bottomAlphabetical',
        emptyLineBeforeUnspecified: 'always',
        severity: 'warning',
      },
    ],
  },

  ignoreFiles: [
    '**/node_modules/**',
    '**/dist/**',
    '**/public/**',
    '**/coverage/**',
  ],
}
